source 'https://rubygems.org'
ruby '2.1.0'

gem 'rails', '4.1.1'
gem 'sqlite3'

gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails', '~> 3.1.0'
gem 'turbolinks', '~> 2.2.2'
gem 'jbuilder', '~> 2.0'
gem 'bootstrap-sass', '~> 3.1.1.1'
gem 'momentjs-rails', '~> 2.5.0'
gem 'bootstrap3-datetimepicker-rails', '~> 3.0.0.1'
gem 'simple_form', '~> 3.1.0.rc1'
